### ISSUE TITLE
Unexpected notification drawer open

### ISSUE THREAD

**Issue by hjek** [peterfajdiga/FastDraw#38]
Launching an app from Fastdraw often causes the notification drawer to open as well. I've encountered this issue on different devices. I'm not sure of the exact circumstances to trigger this but it happens fairly often. However, it's just a mild annoyance.

**Comment by peterfajdiga** [comment]
Thanks for the report! Should be fixed now, can you verify? Attaching an apk with the fix.
[app-release.zip](https://github.com/user-attachments/files/16993303/app-release.zip)

**Comment by hjek** [comment]
Thanks a lot for giving it a look. Unfortunately it's still happening in that `app-release.zip` version.

**Comment by peterfajdiga** [comment]
Which Android version are you running?

**Comment by hjek** [comment]
13

**Comment by peterfajdiga** [comment]
Is there a specific pattern that triggers it? For example maybe you have to first touch an app icon (or empty area) higher up on the screen and then touch (and launch) an app icon lower on the screen. Are you using a finger, a stylus or maybe a mouse?

**Comment by hjek** [comment]
> Are you using a finger, a stylus or maybe a mouse?

Finger.

> Is there a specific pattern that triggers it?

I'm trying to figure this out, but so far can't see any pattern in it at all. If I find out, I'll let you know.
